-- seed_variations_full.sql
-- 生成元: ユーザー提供のBASE商品情報CSVエクスポート(2026-07-12、旧価格・カスタマイズ料を除く35商品523種類)。
-- seed_products.sql投入時点の暫定variations(LITE 2商品のみ、注文CSVから逆算した推定3機種)を、
-- 実際の商品ページCSVに基づく完全なバリエーション一覧で置き換える。
-- 適用条件: order_items作成前(開発段階)のみ実行可(variations削除を伴うため)。
-- accepting_ordersは全件true(受注制御はsettings.accepting_orders_globalとA-14の個別トグルで行う)。
--
-- 【注記】アップロード元データはApple Pencil用2商品(applepencil-cork-lite/applepencil-wood-pro)についても
-- 各1行を含んでいたが、name_ja/name_enが空文字・makerが'OTHER'(誤り、正しくは'APPLE')だったため、
-- この2商品分は投入対象から除外した。既存のseed_products.sqlが投入する
-- 「Apple Pencil / APPLE」の意味のある1行をそのまま維持する(空文字での上書きによる劣化を回避)。
-- Apple Pencil側の正式なバリエーション(世代・製品仕様等)が判明次第、A-14または別途スクリプトで追加すること。
begin;

create temporary table tmp_variations_source (
  code text, name_ja text, name_en text, maker text, model_code text, sort_order int
);

insert into tmp_variations_source (code, name_ja, name_en, maker, model_code, sort_order) values
  ('wazai-kisosugi', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 10),
  ('wazai-kisosugi', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 20),
  ('wazai-kisosugi', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 30),
  ('wazai-kisosugi', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 40),
  ('wazai-kisosugi', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 50),
  ('wazai-kisosugi', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 60),
  ('wazai-kisosugi', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 70),
  ('wazai-kisosugi', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 80),
  ('wazai-kisosugi', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 90),
  ('wazai-kisosugi', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 100),
  ('wazai-kisosugi', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 110),
  ('wazai-kisosugi', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 120),
  ('wazai-kisosugi', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 130),
  ('wazai-kisosugi', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 140),
  ('wazai-kisosugi', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 150),
  ('wazai-kisosugi', '【Wacom】Pro Pen 3D用　KP-505', '【Wacom】Pro Pen 3D用　KP-505', 'WACOM', 'KP-505', 160),
  ('wazai-kisosugi', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 170),
  ('wazai-ichii', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 10),
  ('wazai-ichii', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 20),
  ('wazai-ichii', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 30),
  ('wazai-ichii', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 40),
  ('wazai-ichii', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 50),
  ('wazai-ichii', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 60),
  ('wazai-ichii', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 70),
  ('wazai-ichii', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 80),
  ('wazai-ichii', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 90),
  ('wazai-ichii', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 100),
  ('wazai-ichii', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 110),
  ('wazai-ichii', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 120),
  ('wazai-ichii', '【Wacom】標準ペン用　KP−501E-01X', '【Wacom】標準ペン用　KP−501E-01X', 'WACOM', null, 130),
  ('wazai-ichii', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 140),
  ('wazai-ichii', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 150),
  ('wazai-jindai-kuri', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 10),
  ('wazai-jindai-kuri', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 20),
  ('wazai-jindai-kuri', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 30),
  ('wazai-jindai-kuri', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 40),
  ('wazai-jindai-kuri', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 50),
  ('wazai-jindai-kuri', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 60),
  ('wazai-jindai-kuri', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 70),
  ('wazai-jindai-kuri', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 80),
  ('wazai-jindai-kuri', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 90),
  ('wazai-jindai-kuri', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 100),
  ('wazai-jindai-kuri', '【Wacom】標準ペン用　KP−501E-01X', '【Wacom】標準ペン用　KP−501E-01X', 'WACOM', null, 110),
  ('wazai-jindai-kuri', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 120),
  ('wazai-jindai-kuri', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 130),
  ('wazai-jindai-kuri', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 140),
  ('pro-manilkara', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 10),
  ('pro-manilkara', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 20),
  ('pro-manilkara', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 30),
  ('pro-manilkara', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 40),
  ('pro-manilkara', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 50),
  ('pro-manilkara', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 60),
  ('pro-manilkara', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 70),
  ('pro-manilkara', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 80),
  ('pro-manilkara', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 90),
  ('pro-manilkara', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 100),
  ('pro-manilkara', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 110),
  ('pro-manilkara', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 120),
  ('pro-manilkara', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 130),
  ('pro-manilkara', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 140),
  ('pro-manilkara', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 150),
  ('pro-manilkara', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 160),
  ('pro-manilkara', '【Wacom】Intuos３付属ペン用', '【Wacom】Intuos３付属ペン用', 'WACOM', null, 170),
  ('lite-white', '【Wacom】アートペン KP-701E-01X 【Wacom】Pro Pen３ （軸の中に替芯）', '【Wacom】アートペン KP-701E-01X 【Wacom】Pro Pen３ （軸の中に替芯）', 'WACOM', 'KP-701E', 10),
  ('lite-white', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 20),
  ('lite-white', '【Wacom】Wacom Pen 4K', '【Wacom】Wacom Pen 4K', 'WACOM', null, 30),
  ('lite-white', '【Wacom】筆圧ペン Inuos LP-190-0K', '【Wacom】筆圧ペン Inuos LP-190-0K', 'WACOM', 'LP-190', 40),
  ('lite-white', '【Wacom】Wacom One スタンダードペン（ホワイト/グレー）CP92303B2Z', '【Wacom】Wacom One スタンダードペン（ホワイト/グレー）CP92303B2Z', 'WACOM', 'CP92303B2Z', 50),
  ('lite-white', '【Wacom】Wacom One Pen (白黒軸）CP91300B2Z', '【Wacom】Wacom One Pen (白黒軸）CP91300B2Z', 'WACOM', 'CP91300B2Z', 60),
  ('lite-white', '【Wacom】Intuos３付属ペン', '【Wacom】Intuos３付属ペン', 'WACOM', null, 70),
  ('lite-white', '【XP-PEN】PA１', '【XP-PEN】PA１', 'XPPEN', null, 80),
  ('lite-white', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 90),
  ('lite-white', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 100),
  ('lite-white', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 110),
  ('lite-white', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 120),
  ('lite-white', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 130),
  ('lite-white', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 140),
  ('lite-white', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 150),
  ('lite-white', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 160),
  ('lite-white', '【Wacom】Pro Pen３ （軸の中におもり）ACP50000DZ', '【Wacom】Pro Pen３ （軸の中におもり）ACP50000DZ', 'WACOM', 'ACP50000DZ', 170),
  ('lite-white', '【Wacom】Pro Pen３ （軸の中に替芯）', '【Wacom】Pro Pen３ （軸の中に替芯）', 'WACOM', null, 180),
  ('lite-white', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 190),
  ('lite-white', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 200),
  ('lite-white', '【Wacom】標準ペン KP−501E-01X　', '【Wacom】標準ペン KP−501E-01X　', 'WACOM', null, 210),
  ('lite-white', '【Wacom】Pro Pen 3D  KP-505 ', '【Wacom】Pro Pen 3D  KP-505 ', 'WACOM', 'KP-505', 220),
  ('lite-brown', '【Wacom】アートペン KP-701E-01X ', '【Wacom】アートペン KP-701E-01X ', 'WACOM', 'KP-701E', 10),
  ('lite-brown', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 20),
  ('lite-brown', '【Wacom】Wacom Pen 4K', '【Wacom】Wacom Pen 4K', 'WACOM', null, 30),
  ('lite-brown', '【Wacom】筆圧ペン Inuos LP-190-0K', '【Wacom】筆圧ペン Inuos LP-190-0K', 'WACOM', 'LP-190', 40),
  ('lite-brown', '【Wacom】Wacom One スタンダードペン（ホワイト/グレー）CP92303B2Z', '【Wacom】Wacom One スタンダードペン（ホワイト/グレー）CP92303B2Z', 'WACOM', 'CP92303B2Z', 50),
  ('lite-brown', '【Wacom】Wacom One Pen (白黒軸）CP91300B2Z', '【Wacom】Wacom One Pen (白黒軸）CP91300B2Z', 'WACOM', 'CP91300B2Z', 60),
  ('lite-brown', '【XP-PEN】PA１', '【XP-PEN】PA１', 'XPPEN', null, 70),
  ('lite-brown', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 80),
  ('lite-brown', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 90),
  ('lite-brown', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 100),
  ('lite-brown', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 110),
  ('lite-brown', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 120),
  ('lite-brown', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 130),
  ('lite-brown', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 140),
  ('lite-brown', '【Wacom】Pro Pen３ （軸の中におもり）ACP50000DZ', '【Wacom】Pro Pen３ （軸の中におもり）ACP50000DZ', 'WACOM', 'ACP50000DZ', 150),
  ('lite-brown', '【Wacom】Pro Pen３ （軸の中に替芯）', '【Wacom】Pro Pen３ （軸の中に替芯）', 'WACOM', null, 160),
  ('lite-brown', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 170),
  ('lite-brown', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 180),
  ('lite-brown', '【Wacom】標準ペン KP−501E-01X　', '【Wacom】標準ペン KP−501E-01X　', 'WACOM', null, 190),
  ('lite-brown', '【Wacom】Pro Pen 3D  KP-505 ', '【Wacom】Pro Pen 3D  KP-505 ', 'WACOM', 'KP-505', 200),
  ('wazai-yakusugi', '【Wacom】Intuos３付属ペン用', '【Wacom】Intuos３付属ペン用', 'WACOM', null, 10),
  ('wazai-yakusugi', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 20),
  ('wazai-yakusugi', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 30),
  ('wazai-yakusugi', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 40),
  ('wazai-yakusugi', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 50),
  ('wazai-yakusugi', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 60),
  ('wazai-yakusugi', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 70),
  ('wazai-yakusugi', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 80),
  ('wazai-yakusugi', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 90),
  ('wazai-yakusugi', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 100),
  ('wazai-yakusugi', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 110),
  ('wazai-yakusugi', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 120),
  ('wazai-yakusugi', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 130),
  ('wazai-yakusugi', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 140),
  ('wazai-yakusugi', '【Wacom】標準ペン用　KP−501E-01X', '【Wacom】標準ペン用　KP−501E-01X', 'WACOM', null, 150),
  ('wazai-yakusugi', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 160),
  ('wazai-yakusugi', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 170),
  ('wazai-keyaki', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 10),
  ('wazai-keyaki', '【Wacom】標準ペン用　KP−501E-01X', '【Wacom】標準ペン用　KP−501E-01X', 'WACOM', null, 20),
  ('wazai-keyaki', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 30),
  ('wazai-keyaki', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 40),
  ('wazai-keyaki', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 50),
  ('wazai-keyaki', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 60),
  ('wazai-keyaki', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 70),
  ('wazai-keyaki', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 80),
  ('wazai-keyaki', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 90),
  ('wazai-keyaki', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 100),
  ('wazai-keyaki', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 110),
  ('wazai-keyaki', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 120),
  ('wazai-keyaki', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 130),
  ('wazai-keyaki', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 140),
  ('wazai-keyaki', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 150),
  ('wazai-keyaki', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 160),
  ('wazai-keyaki', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 170),
  ('wazai-enju', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 10),
  ('wazai-enju', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 20),
  ('wazai-enju', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 30),
  ('wazai-enju', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 40),
  ('wazai-enju', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 50),
  ('wazai-enju', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 60),
  ('wazai-enju', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 70),
  ('wazai-enju', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 80),
  ('wazai-enju', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 90),
  ('wazai-enju', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 100),
  ('wazai-enju', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 110),
  ('wazai-enju', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 120),
  ('wazai-enju', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 130),
  ('wazai-enju', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 140),
  ('wazai-enju', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 150),
  ('wazai-enju', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 160),
  ('wazai-enju', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 170),
  ('wazai-shirakashi', '【Wacom】標準ペン用　KP−501E-01X', '【Wacom】標準ペン用　KP−501E-01X', 'WACOM', null, 10),
  ('wazai-shirakashi', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 20),
  ('wazai-shirakashi', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 30),
  ('wazai-shirakashi', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 40),
  ('wazai-shirakashi', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 50),
  ('wazai-shirakashi', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 60),
  ('wazai-shirakashi', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 70),
  ('wazai-shirakashi', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 80),
  ('wazai-shirakashi', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 90),
  ('wazai-shirakashi', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 100),
  ('wazai-shirakashi', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 110),
  ('wazai-shirakashi', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 120),
  ('wazai-shirakashi', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 130),
  ('wazai-shirakashi', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 140),
  ('wazai-shirakashi', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 150),
  ('wazai-shirakashi', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 160),
  ('wazai-jindai-kurumi', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 10),
  ('wazai-jindai-kurumi', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 20),
  ('wazai-jindai-kurumi', '【Wacom】アートペン用　KP-701E-01X', '【Wacom】アートペン用　KP-701E-01X', 'WACOM', 'KP-701E', 30),
  ('wazai-jindai-kurumi', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 40),
  ('wazai-jindai-kurumi', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 50),
  ('wazai-jindai-kurumi', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 60),
  ('wazai-jindai-kurumi', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 70),
  ('wazai-jindai-kurumi', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 80),
  ('wazai-jindai-kurumi', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 90),
  ('wazai-jindai-kurumi', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 100),
  ('wazai-jindai-kurumi', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 110),
  ('wazai-jindai-kurumi', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 120),
  ('wazai-jindai-kurumi', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 130),
  ('wazai-jindai-kurumi', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 140),
  ('wazai-jindai-kurumi', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 150),
  ('wazai-jindai-kurumi', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 160),
  ('wazai-jindai-kurumi', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 170),
  ('wazai-jindai-keyaki', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 10),
  ('wazai-jindai-keyaki', '【Wacom】標準ペン用　KP−501E-01X', '【Wacom】標準ペン用　KP−501E-01X', 'WACOM', null, 20),
  ('wazai-jindai-keyaki', '【Wacom】Pro Pen 3D用　KP-505', '【Wacom】Pro Pen 3D用　KP-505', 'WACOM', 'KP-505', 30),
  ('wazai-jindai-keyaki', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 40),
  ('wazai-jindai-keyaki', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 50),
  ('wazai-jindai-keyaki', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 60),
  ('wazai-jindai-keyaki', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 70),
  ('wazai-jindai-keyaki', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 80),
  ('wazai-jindai-keyaki', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 90),
  ('wazai-jindai-keyaki', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 100),
  ('wazai-jindai-keyaki', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 110),
  ('wazai-jindai-keyaki', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 120),
  ('wazai-jindai-keyaki', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 130),
  ('wazai-jindai-keyaki', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 140),
  ('wazai-jindai-keyaki', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 150),
  ('wazai-jindai-keyaki', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 160),
  ('ergo-inverted', 'プロペン3 ACP50000DZ用　スイッチ穴あり', 'プロペン3 ACP50000DZ用　スイッチ穴あり', 'OTHER', 'ACP50000DZ', 10),
  ('ergo-inverted', 'プロペン3 ACP50000DZ用　スイッチ穴なし', 'プロペン3 ACP50000DZ用　スイッチ穴なし', 'OTHER', 'ACP50000DZ', 20),
  ('ergo-inverted', 'プロペン２ KP-504E用 スイッチ穴あり 2EIB', 'プロペン２ KP-504E用 スイッチ穴あり 2EIB', 'OTHER', 'KP-504E', 30),
  ('ergo-inverted', 'プロペン２ KP-504E用 スイッチ穴なし 2EIN ', 'プロペン２ KP-504E用 スイッチ穴なし 2EIN ', 'OTHER', 'KP-504E', 40),
  ('ergo-inverted', 'プロペン KP-503E用 スイッチ穴あり PEIB', 'プロペン KP-503E用 スイッチ穴あり PEIB', 'OTHER', 'KP-503E', 50),
  ('ergo-inverted', 'プロペン KP-503E用 スイッチ穴なし PEIN', 'プロペン KP-503E用 スイッチ穴なし PEIN', 'OTHER', 'KP-503E', 60),
  ('ergo-inverted', '標準ペン KP−501E-01X用 スイッチ穴あり GEIB', '標準ペン KP−501E-01X用 スイッチ穴あり GEIB', 'OTHER', null, 70),
  ('ergo-inverted', '標準ペン KP−501E-01X用 スイッチ穴なし GEIN', '標準ペン KP−501E-01X用 スイッチ穴なし GEIN', 'OTHER', null, 80),
  ('ergo-inverted', 'プロペン 3D  KP-505用 スイッチあり 3EIB', 'プロペン 3D  KP-505用 スイッチあり 3EIB', 'OTHER', 'KP-505', 90),
  ('ergo-inverted', 'アートペン KP-701E-01X用 スイッチあり AEIB', 'アートペン KP-701E-01X用 スイッチあり AEIB', 'OTHER', 'KP-701E', 100),
  ('ergo-inverted', 'アートペン KP-701E-01X用 スイッチなし AEIN', 'アートペン KP-701E-01X用 スイッチなし AEIN', 'OTHER', 'KP-701E', 110),
  ('ergo-thick', 'プロペン3 ACP50000DZ用　スイッチ穴あり', 'プロペン3 ACP50000DZ用　スイッチ穴あり', 'OTHER', 'ACP50000DZ', 10),
  ('ergo-thick', 'プロペン3 ACP50000DZ用　スイッチ穴なし', 'プロペン3 ACP50000DZ用　スイッチ穴なし', 'OTHER', 'ACP50000DZ', 20),
  ('ergo-thick', 'プロペン２ KP-504E用 スイッチ穴あり 2EFB', 'プロペン２ KP-504E用 スイッチ穴あり 2EFB', 'OTHER', 'KP-504E', 30),
  ('ergo-thick', 'プロペン２ KP-504E用 スイッチ穴なし 2EFN ', 'プロペン２ KP-504E用 スイッチ穴なし 2EFN ', 'OTHER', 'KP-504E', 40),
  ('ergo-thick', 'プロペン KP-503E用 スイッチ穴あり PEFB', 'プロペン KP-503E用 スイッチ穴あり PEFB', 'OTHER', 'KP-503E', 50),
  ('ergo-thick', 'プロペン KP-503E用 スイッチ穴なし PEFN', 'プロペン KP-503E用 スイッチ穴なし PEFN', 'OTHER', 'KP-503E', 60),
  ('ergo-thick', '標準ペン KP−501E-01X用 スイッチ穴あり GEFB', '標準ペン KP−501E-01X用 スイッチ穴あり GEFB', 'OTHER', null, 70),
  ('ergo-thick', '標準ペン KP−501E-01X用 スイッチ穴なし GEFN', '標準ペン KP−501E-01X用 スイッチ穴なし GEFN', 'OTHER', null, 80),
  ('ergo-thick', 'プロペン 3D  KP-505用 スイッチあり 3EFB', 'プロペン 3D  KP-505用 スイッチあり 3EFB', 'OTHER', 'KP-505', 90),
  ('ergo-thick', 'アートペン KP-701E-01X用 スイッチあり AEFB', 'アートペン KP-701E-01X用 スイッチあり AEFB', 'OTHER', 'KP-701E', 100),
  ('ergo-thick', 'アートペン KP-701E-01X用 スイッチなし AEIFN', 'アートペン KP-701E-01X用 スイッチなし AEIFN', 'OTHER', 'KP-701E', 110),
  ('premium-tokusen-kokutan', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 10),
  ('premium-tokusen-kokutan', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 20),
  ('premium-tokusen-kokutan', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 30),
  ('premium-tokusen-kokutan', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 40),
  ('premium-tokusen-kokutan', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 50),
  ('premium-tokusen-kokutan', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 60),
  ('premium-tokusen-kokutan', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 70),
  ('premium-tokusen-kokutan', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 80),
  ('premium-tokusen-kokutan', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 90),
  ('premium-tokusen-kokutan', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 100),
  ('premium-tokusen-kokutan', '【Wacom】標準ペン KP−501E-01X', '【Wacom】標準ペン KP−501E-01X', 'WACOM', null, 110),
  ('premium-tokusen-kokutan', '【Wacom】Pro Pen 3D  KP-505', '【Wacom】Pro Pen 3D  KP-505', 'WACOM', 'KP-505', 120),
  ('premium-tokusen-kokutan', '【Wacom】アートペン KP-701E-01X', '【Wacom】アートペン KP-701E-01X', 'WACOM', 'KP-701E', 130),
  ('premium-tokusen-kokutan', '【Wacom】Intuos３付属ペン ', '【Wacom】Intuos３付属ペン ', 'WACOM', null, 140),
  ('premium-tokusen-kokutan', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 150),
  ('premium-tokusen-kokutan', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 160),
  ('premium-shamkaki', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 10),
  ('premium-shamkaki', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 20),
  ('premium-shamkaki', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 30),
  ('premium-shamkaki', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 40),
  ('premium-shamkaki', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 50),
  ('premium-shamkaki', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 60),
  ('premium-shamkaki', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 70),
  ('premium-shamkaki', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 80),
  ('premium-shamkaki', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 90),
  ('premium-shamkaki', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 100),
  ('premium-shamkaki', '【Wacom】標準ペン KP−501E-01X', '【Wacom】標準ペン KP−501E-01X', 'WACOM', null, 110),
  ('premium-shamkaki', '【Wacom】Pro Pen 3D  KP-505 ', '【Wacom】Pro Pen 3D  KP-505 ', 'WACOM', 'KP-505', 120),
  ('premium-shamkaki', '【Wacom】アートペン KP-701E-01X ', '【Wacom】アートペン KP-701E-01X ', 'WACOM', 'KP-701E', 130),
  ('premium-shamkaki', '【Wacom】Intuos３付属ペン ', '【Wacom】Intuos３付属ペン ', 'WACOM', null, 140),
  ('premium-shamkaki', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 150),
  ('premium-shamkaki', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 160),
  ('premium-purpleheart', '【Wacom】Intuos３付属ペン', '【Wacom】Intuos３付属ペン', 'WACOM', null, 10),
  ('premium-purpleheart', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 20),
  ('premium-purpleheart', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 30),
  ('premium-purpleheart', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 40),
  ('premium-purpleheart', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 50),
  ('premium-purpleheart', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 60),
  ('premium-purpleheart', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 70),
  ('premium-purpleheart', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 80),
  ('premium-purpleheart', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 90),
  ('premium-purpleheart', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 100),
  ('premium-purpleheart', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 110),
  ('premium-purpleheart', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 120),
  ('premium-purpleheart', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 130),
  ('premium-purpleheart', '【Wacom】標準ペン KP−501E-01X', '【Wacom】標準ペン KP−501E-01X', 'WACOM', null, 140),
  ('premium-purpleheart', '【Wacom】Pro Pen 3D  KP-505', '【Wacom】Pro Pen 3D  KP-505', 'WACOM', 'KP-505', 150),
  ('premium-purpleheart', '【Wacom】アートペン KP-701E-01X', '【Wacom】アートペン KP-701E-01X', 'WACOM', 'KP-701E', 160),
  ('premium-karin-kobu', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 10),
  ('premium-karin-kobu', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 20),
  ('premium-karin-kobu', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 30),
  ('premium-karin-kobu', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 40),
  ('premium-karin-kobu', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 50),
  ('premium-karin-kobu', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 60),
  ('premium-karin-kobu', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 70),
  ('premium-karin-kobu', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 80),
  ('premium-karin-kobu', '【Wacom】標準ペン KP−501E-01X　', '【Wacom】標準ペン KP−501E-01X　', 'WACOM', null, 90),
  ('premium-karin-kobu', '【Wacom】Pro Pen 3D  KP-505 ', '【Wacom】Pro Pen 3D  KP-505 ', 'WACOM', 'KP-505', 100),
  ('premium-karin-kobu', '【Wacom】アートペン KP-701E-01X', '【Wacom】アートペン KP-701E-01X', 'WACOM', 'KP-701E', 110),
  ('premium-karin-kobu', '【Wacom】Intuos３付属ペン ', '【Wacom】Intuos３付属ペン ', 'WACOM', null, 120),
  ('premium-karin-kobu', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 130),
  ('premium-karin-kobu', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 140),
  ('pro-european-beech', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 10),
  ('pro-european-beech', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 20),
  ('pro-european-beech', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 30),
  ('pro-european-beech', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 40),
  ('pro-european-beech', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 50),
  ('pro-european-beech', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 60),
  ('pro-european-beech', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 70),
  ('pro-european-beech', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 80),
  ('pro-european-beech', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 90),
  ('pro-european-beech', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 100),
  ('pro-european-beech', '【Wacom】標準ペン用　KP−501E-01X', '【Wacom】標準ペン用　KP−501E-01X', 'WACOM', null, 110),
  ('pro-european-beech', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 120),
  ('pro-european-beech', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 130),
  ('pro-european-beech', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 140),
  ('pro-european-beech', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 150),
  ('pro-european-beech', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 160),
  ('pro-walnut', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('pro-walnut', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 20),
  ('pro-walnut', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 30),
  ('pro-walnut', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 40),
  ('pro-walnut', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 50),
  ('pro-walnut', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 60),
  ('pro-walnut', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 70),
  ('pro-walnut', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 80),
  ('pro-walnut', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 90),
  ('pro-walnut', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 100),
  ('pro-walnut', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 110),
  ('pro-walnut', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 120),
  ('pro-walnut', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 130),
  ('pro-walnut', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 140),
  ('pro-walnut', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 150),
  ('pro-walnut', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 160),
  ('pro-monkeypod', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('pro-monkeypod', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 20),
  ('pro-monkeypod', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 30),
  ('pro-monkeypod', '【Wacom】標準ペン用　KP−501E-01X', '【Wacom】標準ペン用　KP−501E-01X', 'WACOM', null, 40),
  ('pro-monkeypod', '【Wacom】Pro Pen 3D用　KP-505', '【Wacom】Pro Pen 3D用　KP-505', 'WACOM', 'KP-505', 50),
  ('pro-monkeypod', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 60),
  ('pro-monkeypod', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 70),
  ('pro-monkeypod', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 80),
  ('pro-monkeypod', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 90),
  ('pro-monkeypod', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 100),
  ('pro-monkeypod', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 110),
  ('pro-monkeypod', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 120),
  ('pro-monkeypod', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 130),
  ('pro-monkeypod', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 140),
  ('pro-monkeypod', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 150),
  ('pro-monkeypod', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 160),
  ('wazai-ogasawara-kuwa', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('wazai-ogasawara-kuwa', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 20),
  ('wazai-ogasawara-kuwa', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 30),
  ('wazai-ogasawara-kuwa', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 40),
  ('wazai-ogasawara-kuwa', '【Wacom】Pro Pen 3D用　KP-505', '【Wacom】Pro Pen 3D用　KP-505', 'WACOM', 'KP-505', 50),
  ('wazai-ogasawara-kuwa', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 60),
  ('wazai-ogasawara-kuwa', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 70),
  ('wazai-ogasawara-kuwa', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 80),
  ('wazai-ogasawara-kuwa', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 90),
  ('wazai-ogasawara-kuwa', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 100),
  ('wazai-ogasawara-kuwa', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 110),
  ('wazai-ogasawara-kuwa', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 120),
  ('wazai-ogasawara-kuwa', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 130),
  ('wazai-ogasawara-kuwa', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 140),
  ('pro-philippine-mahogany', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('pro-philippine-mahogany', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 20),
  ('pro-philippine-mahogany', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 30),
  ('pro-philippine-mahogany', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 40),
  ('pro-philippine-mahogany', '【Wacom】Pro Pen 3D用　KP-505', '【Wacom】Pro Pen 3D用　KP-505', 'WACOM', 'KP-505', 50),
  ('pro-philippine-mahogany', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 60),
  ('pro-philippine-mahogany', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 70),
  ('pro-philippine-mahogany', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 80),
  ('pro-philippine-mahogany', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 90),
  ('pro-philippine-mahogany', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 100),
  ('pro-philippine-mahogany', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 110),
  ('pro-philippine-mahogany', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 120),
  ('pro-philippine-mahogany', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 130),
  ('pro-philippine-mahogany', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 140),
  ('pro-philippine-mahogany', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 150),
  ('pro-philippine-mahogany', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 160),
  ('pro-philippine-mahogany', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 170),
  ('pro-lenke', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('pro-lenke', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 20),
  ('pro-lenke', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 30),
  ('pro-lenke', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 40),
  ('pro-lenke', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 50),
  ('pro-lenke', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 60),
  ('pro-lenke', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 70),
  ('pro-lenke', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 80),
  ('pro-lenke', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 90),
  ('pro-lenke', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 100),
  ('pro-lenke', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 110),
  ('pro-lenke', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 120),
  ('pro-lenke', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 130),
  ('pro-lenke', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 140),
  ('pro-lenke', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 150),
  ('pro-lenke', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 160),
  ('pro-lenke', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 170),
  ('premium-karin', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('premium-karin', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 20),
  ('premium-karin', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 30),
  ('premium-karin', '【Wacom】標準ペン KP−501E-01X　', '【Wacom】標準ペン KP−501E-01X　', 'WACOM', null, 40),
  ('premium-karin', '【Wacom】Pro Pen 3D  KP-505 ', '【Wacom】Pro Pen 3D  KP-505 ', 'WACOM', 'KP-505', 50),
  ('premium-karin', '【Wacom】アートペン KP-701E-01X', '【Wacom】アートペン KP-701E-01X', 'WACOM', 'KP-701E', 60),
  ('premium-karin', '【Wacom】Intuos３付属ペン ', '【Wacom】Intuos３付属ペン ', 'WACOM', null, 70),
  ('premium-karin', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 80),
  ('premium-karin', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 90),
  ('premium-karin', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 100),
  ('premium-karin', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 110),
  ('premium-karin', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 120),
  ('premium-karin', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 130),
  ('premium-karin', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 140),
  ('premium-karin', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 150),
  ('premium-koh-shitan', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('premium-koh-shitan', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 20),
  ('premium-koh-shitan', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 30),
  ('premium-koh-shitan', '【Wacom】標準ペン KP−501E-01X　', '【Wacom】標準ペン KP−501E-01X　', 'WACOM', null, 40),
  ('premium-koh-shitan', '【Wacom】Pro Pen 3D  KP-505 ', '【Wacom】Pro Pen 3D  KP-505 ', 'WACOM', 'KP-505', 50),
  ('premium-koh-shitan', '【Wacom】アートペン KP-701E-01X', '【Wacom】アートペン KP-701E-01X', 'WACOM', 'KP-701E', 60),
  ('premium-koh-shitan', '【Wacom】Intuos３付属ペン ', '【Wacom】Intuos３付属ペン ', 'WACOM', null, 70),
  ('premium-koh-shitan', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 80),
  ('premium-koh-shitan', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 90),
  ('premium-koh-shitan', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 100),
  ('premium-koh-shitan', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 110),
  ('premium-koh-shitan', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 120),
  ('premium-koh-shitan', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 130),
  ('premium-koh-shitan', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 140),
  ('premium-koh-shitan', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 150),
  ('wazai-yamazakura', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('wazai-yamazakura', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 20),
  ('wazai-yamazakura', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 30),
  ('wazai-yamazakura', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 40),
  ('wazai-yamazakura', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 50),
  ('wazai-yamazakura', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 60),
  ('wazai-yamazakura', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 70),
  ('wazai-yamazakura', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 80),
  ('wazai-yamazakura', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 90),
  ('wazai-yamazakura', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 100),
  ('wazai-yamazakura', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 110),
  ('wazai-yamazakura', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 120),
  ('wazai-yamazakura', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 130),
  ('wazai-yamazakura', '【XP-PEN】X3PRO', '【XP-PEN】X3PRO', 'XPPEN', null, 140),
  ('wazai-yamazakura', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 150),
  ('wazai-yamazakura', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 160),
  ('pro-white-oak', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('pro-white-oak', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 20),
  ('pro-white-oak', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 30),
  ('pro-white-oak', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 40),
  ('pro-white-oak', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 50),
  ('pro-white-oak', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 60),
  ('pro-white-oak', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 70),
  ('pro-white-oak', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 80),
  ('pro-white-oak', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 90),
  ('pro-white-oak', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 100),
  ('pro-white-oak', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 110),
  ('pro-white-oak', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 120),
  ('pro-white-oak', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 130),
  ('pro-white-oak', '【XcenceLabs】PH5-A用', '【XcenceLabs】PH5-A用', 'OTHER', null, 140),
  ('pro-white-oak', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 150),
  ('pro-white-oak', '【XP-PEN】X3 PRO用', '【XP-PEN】X3 PRO用', 'XPPEN', null, 160),
  ('pro-white-oak', '【XP-PEN】X3PROスリムペン', '【XP-PEN】X3PROスリムペン', 'XPPEN', null, 170),
  ('pro-wenge', '【Wacom】Pro Pen３用　ACP50000DZ', '【Wacom】Pro Pen３用　ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('pro-wenge', '【Wacom】Pro Pen ２用　 KP-504E', '【Wacom】Pro Pen ２用　 KP-504E', 'WACOM', 'KP-504E', 20),
  ('pro-wenge', '【Wacom】Pro Pen 用　KP-503E', '【Wacom】Pro Pen 用　KP-503E', 'WACOM', 'KP-503E', 30),
  ('pro-wenge', '【Wacom】標準ペン用　KP−501E-01X　', '【Wacom】標準ペン用　KP−501E-01X　', 'WACOM', null, 40),
  ('pro-wenge', '【Wacom】Pro Pen 3D用　KP-505 ', '【Wacom】Pro Pen 3D用　KP-505 ', 'WACOM', 'KP-505', 50),
  ('pro-wenge', '【Wacom】アートペン用　KP-701E-01X ', '【Wacom】アートペン用　KP-701E-01X ', 'WACOM', 'KP-701E', 60),
  ('pro-wenge', '【Wacom】Intuos３付属ペン用 ', '【Wacom】Intuos３付属ペン用 ', 'WACOM', null, 70),
  ('pro-wenge', '【XP-PEN】PA1用', '【XP-PEN】PA1用', 'XPPEN', null, 80),
  ('pro-wenge', '【XP-PEN】PA2用', '【XP-PEN】PA2用', 'XPPEN', null, 90),
  ('pro-wenge', '【XP-PEN】PA5用', '【XP-PEN】PA5用', 'XPPEN', null, 100),
  ('pro-wenge', '【XP-PEN】PA6用', '【XP-PEN】PA6用', 'XPPEN', null, 110),
  ('pro-wenge', '【XP-PEN】P02S用', '【XP-PEN】P02S用', 'XPPEN', null, 120),
  ('pro-wenge', '【XP-PEN】P05/P05S/P05R用', '【XP-PEN】P05/P05S/P05R用', 'XPPEN', null, 130),
  ('pro-wenge', '【XenceLabs】PH5-A用', '【XenceLabs】PH5-A用', 'XENCELABS', null, 140),
  ('pro-wenge', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 150),
  ('premium-honduras-mahogany', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('premium-honduras-mahogany', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 20),
  ('premium-honduras-mahogany', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 30),
  ('premium-honduras-mahogany', '【Wacom】標準ペン KP−501E-01X', '【Wacom】標準ペン KP−501E-01X', 'WACOM', null, 40),
  ('premium-honduras-mahogany', '【Wacom】Pro Pen 3D  KP-505', '【Wacom】Pro Pen 3D  KP-505', 'WACOM', 'KP-505', 50),
  ('premium-honduras-mahogany', '【Wacom】アートペン KP-701E-01X', '【Wacom】アートペン KP-701E-01X', 'WACOM', 'KP-701E', 60),
  ('premium-honduras-mahogany', '【Wacom】Intuos３付属ペン', '【Wacom】Intuos３付属ペン', 'WACOM', null, 70),
  ('premium-honduras-mahogany', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 80),
  ('premium-honduras-mahogany', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 90),
  ('premium-honduras-mahogany', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 100),
  ('premium-honduras-mahogany', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 110),
  ('premium-honduras-mahogany', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 120),
  ('premium-honduras-mahogany', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 130),
  ('premium-honduras-mahogany', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 140),
  ('premium-honduras-mahogany', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 150),
  ('premium-shima-kokutan', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('premium-shima-kokutan', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 20),
  ('premium-shima-kokutan', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 30),
  ('premium-shima-kokutan', '【Wacom】標準ペン KP−501E-01X', '【Wacom】標準ペン KP−501E-01X', 'WACOM', null, 40),
  ('premium-shima-kokutan', '【Wacom】Pro Pen 3D  KP-505', '【Wacom】Pro Pen 3D  KP-505', 'WACOM', 'KP-505', 50),
  ('premium-shima-kokutan', '【Wacom】アートペン KP-701E-01X', '【Wacom】アートペン KP-701E-01X', 'WACOM', 'KP-701E', 60),
  ('premium-shima-kokutan', '【Wacom】Intuos３付属ペン ', '【Wacom】Intuos３付属ペン ', 'WACOM', null, 70),
  ('premium-shima-kokutan', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 80),
  ('premium-shima-kokutan', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 90),
  ('premium-shima-kokutan', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 100),
  ('premium-shima-kokutan', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 110),
  ('premium-shima-kokutan', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 120),
  ('premium-shima-kokutan', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 130),
  ('premium-shima-kokutan', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 140),
  ('premium-shima-kokutan', '【Wacom】One by Wacom / Intuos筆圧ペン', '【Wacom】One by Wacom / Intuos筆圧ペン', 'WACOM', null, 150),
  ('premium-hawaiian-koa-plain', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('premium-hawaiian-koa-plain', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 20),
  ('premium-hawaiian-koa-plain', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 30),
  ('premium-hawaiian-koa-plain', '【Wacom】標準ペン KP−501E-01X', '【Wacom】標準ペン KP−501E-01X', 'WACOM', null, 40),
  ('premium-hawaiian-koa-plain', '【Wacom】Pro Pen 3D  KP-505', '【Wacom】Pro Pen 3D  KP-505', 'WACOM', 'KP-505', 50),
  ('premium-hawaiian-koa-plain', '【Wacom】アートペン KP-701E-01X', '【Wacom】アートペン KP-701E-01X', 'WACOM', 'KP-701E', 60),
  ('premium-hawaiian-koa-plain', '【Wacom】Intuos３付属ペン', '【Wacom】Intuos３付属ペン', 'WACOM', null, 70),
  ('premium-hawaiian-koa-plain', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 80),
  ('premium-hawaiian-koa-plain', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 90),
  ('premium-hawaiian-koa-plain', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 100),
  ('premium-hawaiian-koa-plain', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 110),
  ('premium-hawaiian-koa-plain', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 120),
  ('premium-hawaiian-koa-plain', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 130),
  ('premium-hawaiian-koa-plain', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 140),
  ('premium-hawaiian-koa-curly', '【Wacom】Pro Pen３ ACP50000DZ', '【Wacom】Pro Pen３ ACP50000DZ', 'WACOM', 'ACP50000DZ', 10),
  ('premium-hawaiian-koa-curly', '【Wacom】Pro Pen ２ KP-504E', '【Wacom】Pro Pen ２ KP-504E', 'WACOM', 'KP-504E', 20),
  ('premium-hawaiian-koa-curly', '【Wacom】Pro Pen KP-503E', '【Wacom】Pro Pen KP-503E', 'WACOM', 'KP-503E', 30),
  ('premium-hawaiian-koa-curly', '【Wacom】標準ペン KP−501E-01X', '【Wacom】標準ペン KP−501E-01X', 'WACOM', null, 40),
  ('premium-hawaiian-koa-curly', '【Wacom】Pro Pen 3D  KP-505', '【Wacom】Pro Pen 3D  KP-505', 'WACOM', 'KP-505', 50),
  ('premium-hawaiian-koa-curly', '【Wacom】アートペン KP-701E-01X', '【Wacom】アートペン KP-701E-01X', 'WACOM', 'KP-701E', 60),
  ('premium-hawaiian-koa-curly', '【Wacom】Intuos３付属ペン', '【Wacom】Intuos３付属ペン', 'WACOM', null, 70),
  ('premium-hawaiian-koa-curly', '【XP-PEN】PA1', '【XP-PEN】PA1', 'XPPEN', null, 80),
  ('premium-hawaiian-koa-curly', '【XP-PEN】PA2', '【XP-PEN】PA2', 'XPPEN', null, 90),
  ('premium-hawaiian-koa-curly', '【XP-PEN】PA5', '【XP-PEN】PA5', 'XPPEN', null, 100),
  ('premium-hawaiian-koa-curly', '【XP-PEN】PA6', '【XP-PEN】PA6', 'XPPEN', null, 110),
  ('premium-hawaiian-koa-curly', '【XP-PEN】P02S', '【XP-PEN】P02S', 'XPPEN', null, 120),
  ('premium-hawaiian-koa-curly', '【XP-PEN】P05/P05S/P05R', '【XP-PEN】P05/P05S/P05R', 'XPPEN', null, 130),
  ('premium-hawaiian-koa-curly', '【XcenceLabs】PH5-A', '【XcenceLabs】PH5-A', 'OTHER', null, 140)
;

-- このスクリプトが対象とする商品(=tmp_variations_sourceにcodeが存在する商品)のvariationsのみを
-- 削除してから再投入する。対象外の商品(Apple Pencil 2商品)の既存variationsには一切触れない。
delete from variations
where product_id in (
  select p.id from products p
  join tmp_variations_source s on s.code = p.code
);

insert into variations (product_id, name_ja, name_en, maker, model_code, sort_order)
select p.id, s.name_ja, s.name_en, s.maker::pen_maker, s.model_code, s.sort_order
from tmp_variations_source s
join products p on p.code = s.code;

drop table tmp_variations_source;

commit;
